name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: '${{ github.repository }}@v1'
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: '${{ github.repository }}@v1'
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'My Issue (Commit: ${{ github.sha }})'
        body: My Issue Body
        assignees: |
          michael-crawford
          cayman-crawford
